name: Promote image

on:
  workflow_call:
    inputs:
      image_branch:
        required: true
        type: string
      acr_name:
        required: true
        type: string
    outputs:
      image_tag:
        value: ${{ jobs.promote.outputs.image_tag }}

jobs:
  promote:
    runs-on: ubuntu-22.04

    outputs:
      image_tag: ${{ steps.image.outputs.image_tag }}

    steps:
      - name: Get latest matching tag
        id: get_tag
        run: |
          SEARCH="${{ inputs.image_branch }}"

          TAG=$(curl -s https://ghcr.io/v2/dfe-digital/plan-technology-for-your-school/tags/list \
            | jq -r '.tags[]' \
            | grep "$SEARCH" \
            | sort -r \
            | head -n 1)

          if [ -z "$TAG" ]; then
            echo "No matching tag found"
            exit 1
          fi

          echo "Found tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Import image into ACR
        run: |
          az acr import \
            --name ${{ inputs.acr_name }} \
            --source ghcr.io/dfe-digital/plan-technology-for-your-school:${{ steps.get_tag.outputs.tag }} \
            --image plan-technology-for-your-school:${{ steps.get_tag.outputs.tag }} || true

      - name: Get latest image tag
        id: image
        run: |
          IMAGE_TAG=$(az acr repository show-tags \
            --name ${{ inputs.acr_name }} \
            --repository plan-tech-app \
            --top 1 --orderby time_desc | jq -r '.[0]')

          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
