ALTER TABLE dbo.answer
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE dbo.establishmentRecommendationHistory
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE dbo.groupReadActivity
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE dbo.question
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE dbo.recommendation
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE dbo.response
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO

ALTER TABLE dbo.submission
ADD UserActionId UNIQUEIDENTIFIER NULL;
GO