name: Azure CLI Login
description: Login to Azure using service principal

inputs:
  az_tenant_id:
    required: true
    type: string
  az_subscription_id:
    required: true
    type: string
  az_client_id:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Azure CLI Login with Federated Identity
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.az_client_id }}
        tenant-id: ${{ inputs.az_tenant_id }}
        subscription-id: ${{ inputs.az_subscription_id }}