name: Run Database Upgrader
description: Builds and runs the PlanTech database upgrader app

inputs:
  dotnet_version:
    required: true
    type: string
  az_keyvault_name:
    required: true
    type: string
  az_keyvault_database_connectionstring_name:
    required: true
    type: string
  az_sql_database_server_name:
    required: true
    type: string
  az_resource_group_name:
    required: true
    type: string
  environment:
    required: true
    type: string
  sql_analytics_username:
    required: true
    type: string
  sql_analytics_password:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Build database upgrader
      uses: ./.github/actions/build-dotnet-app
      with:
        dotnet_version: ${{ inputs.dotnet_version }}
        solution_filename: Dfe.PlanTech.DatabaseUpgrader.sln

    - name: Get workflow IP address
      id: whats-my-ip
      uses: ./.github/actions/whats-my-ip-address

    - name: Add Azure firewall rules
      shell: bash
      run: |
        az sql server firewall-rule create --resource-group ${{ inputs.az_resource_group_name }} --server ${{ inputs.az_sql_database_server_name }} --name db-upgrader --start-ip-address ${{ steps.whats-my-ip.outputs.ip }} --end-ip-address ${{ steps.whats-my-ip.outputs.ip }} &> /dev/null
        az keyvault network-rule add --resource-group ${{ inputs.az_resource_group_name }} --name ${{ inputs.az_keyvault_name }} --ip-address ${{ steps.whats-my-ip.outputs.ip }} &> /dev/null

    - name: Get connection string
      id: get-db-connection-string
      uses: ./.github/actions/azure-get-keyvault-secret
      with:
        az_keyvault_name: ${{ inputs.az_keyvault_name }}
        az_keyvault_secret_name: ${{ inputs.az_keyvault_database_connectionstring_name }}

    - name: Run database upgrader
      shell: bash
      run: dotnet ./build/Dfe.PlanTech.DatabaseUpgrader.dll -c "${{ steps.get-db-connection-string.outputs.secret_value }}" --env ${{ inputs.environment }} -p Analytics_Username=${{ inputs.sql_analytics_username }} Analytics_Password=${{ inputs.sql_analytics_password }}

    - name: Remove Azure firewall rules
      shell: bash
      if: always()
      run: |
        az sql server firewall-rule delete --resource-group ${{ inputs.az_resource_group_name }} --server ${{ inputs.az_sql_database_server_name }} --name db-upgrader &> /dev/null
        az keyvault network-rule remove --resource-group ${{ inputs.az_resource_group_name }} --name ${{ inputs.az_keyvault_name }} --ip-address ${{ steps.whats-my-ip.outputs.ip }} &> /dev/null
