name: Run mutations tests
description: Runs mutations testing against a solution and publishes them to the workflow runs

inputs:
  solution_path:
    description: "Filepath for the solution to run mutations testing on"
    required: true
  config_path:
    default: ".github/actions/run-mutations-testing/stryker-config.json"
    description: "Relative path for the Stryker Config file to use"

outputs:
  reports_artifact_url:
    description: URL of the uploaded artifact containing the test results
    value: ${{ steps.upload-reults.outputs.artifact-url }}

runs:
  using: composite
  steps:
    - name: Install Stryker tool
      shell: bash
      run: dotnet tool install -g dotnet-stryker

    - name: Run mutations tests
      shell: bash
      run: dotnet stryker -s ${{ inputs.solution_path }} -f .github/actions/run-mutations-testing/stryker-config.json

    - name: Upload results
      id: upload-reults
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mutations-report
        path: StrykerOutput/**/**/*
