import json

def get_unique_content_types(json_data):
    content_types = set()
    
    entries = json_data.get("entries", [])

    for entry in entries:
        content_type = entry.get("sys", {}).get("contentType", {}).get("sys", {}).get("id")
        if content_type:
            content_types.add(content_type)
    
    return list(content_types)

def main(filename):
    try:
        with open(filename, 'r') as file:
            json_data = json.load(file)

        unique_content_types = get_unique_content_types(json_data)

        if unique_content_types:
            print("Unique Content Types:")
            for content_type in unique_content_types:
                print(content_type)
        else:
            print("No content types found in the JSON data.")

    except FileNotFoundError:
        print(f"The '{filename}' file was not found.")
    except json.JSONDecodeError:
        print(f"Error parsing JSON data from the '{filename}' file.")

if __name__ == "__main__":
    filename = "<REPLACE_WITH_EXPORTED_CONTENFUL_JSON>"     # This is the file which is generated by our contentful export, could probably make this and arg which we pass, but for now i've left it as we're using it as a helper.
    main(filename)
