name: Whitelisting for Runner
description: Adds the runner's IP to storage and key vault network rules
inputs:
  runner-ip:
    description: Public IP of the runner
    required: true
  sa-costing-name:
    description: Name of the storage account
    required: true
  sa-costing-resource-group:
    description: Resource group of the storage account
    required: true
  az-keyvault-name:
    description: Name of the application key vault
    required: true
  az-aca-resource-group:
    description: Resource group for the application key vault
    required: true
  tf-backend-resource-group:
    description: Resource group for the Terraform key vault
    required: true
  tf-secrets-keyvault-name:
    description: Name of the Terraform secrets key vault
    required: true
  removeRules:
    description: Remove the IPs from the firewall
    required: true
runs:
  using: 'composite'
  steps:
    - name: Whitelist IP in storage and key vaults
      if: ${{ inputs.removeRules == 'false' }}
      shell: bash
      run: |
        set -euo pipefail

        check_purge_protection_or_die () {
            local rg="$1"
            local name="$2"
            local label="$3"

            echo "Checking purge protection for $label KeyVault ($rg / $name)..."

            local pp=""
            pp="$(az resource show \
                --resource-group "$rg" \
                --name "$name" \
                --resource-type "Microsoft.KeyVault/vaults" \
                --query "properties.enablePurgeProtection" -o tsv || true)"

            if [ "$pp" != "true" ]; then
                echo "$label Key Vault purge protection is not enabled (enablePurgeProtection='$pp'). Azure Policy will deny updates." >&2
                exit 1
            fi
        }

        echo "Adding network rule to costing storage account..."
        az storage account network-rule add \
        --resource-group "${{ inputs.sa-costing-resource-group }}" \
        --account-name "${{ inputs.sa-costing-name }}" \
        --ip-address "${{ inputs.runner-ip }}" > /dev/null

        check_purge_protection_or_die "${{ inputs.az-aca-resource-group }}" "${{ inputs.az-keyvault-name }}" "service"
        echo "Adding network rule to service KeyVault..."
        az keyvault network-rule add \
        --resource-group "${{ inputs.az-aca-resource-group }}" \
        --name "${{ inputs.az-keyvault-name }}" \
        --ip-address "${{ inputs.runner-ip }}" > /dev/null

        check_purge_protection_or_die "${{ inputs.tf-backend-resource-group }}" "${{ inputs.tf-secrets-keyvault-name }}" "terraform"
        echo "Adding network rule to Terraform KeyVault..."
        az keyvault network-rule add \
        --resource-group "${{ inputs.tf-backend-resource-group }}" \
        --name "${{ inputs.tf-secrets-keyvault-name }}" \
        --ip-address "${{ inputs.runner-ip }}" > /dev/null

    - name: Remove IP in storage and key vaults
      if: ${{ inputs.removeRules == 'true' }}
      shell: bash
      run: |
        set -euo pipefail

        az storage account network-rule remove \
          --resource-group "${{ inputs.sa-costing-resource-group }}" \
          --account-name "${{ inputs.sa-costing-name }}" \
          --ip-address "${{ inputs.runner-ip }}" > /dev/null

        az keyvault network-rule remove \
          --resource-group "${{ inputs.az-aca-resource-group }}" \
          --name "${{ inputs.az-keyvault-name }}" \
          --ip-address "${{ inputs.runner-ip }}" > /dev/null

        az keyvault network-rule remove \
          --resource-group "${{ inputs.tf-backend-resource-group }}" \
          --name "${{ inputs.tf-secrets-keyvault-name }}" \
          --ip-address "${{ inputs.runner-ip }}" > /dev/null
