name: Run Cypress E2E tests
description: Run E2E tests using Cypress

inputs:
  url:
    required: true
    type: string
  dsi_url:
    required: true
    type: string
  dsi_username:
    required: true
    type: string
  dsi_password:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Create Cypress config
      shell: bash
      run: |
        echo "{\"URL\": \"${{ inputs.url }}\", \"DSi_Url\": \"${{ inputs.dsi_url }}\", \"DSi_Email\": \"${{ inputs.dsi_username }}\", \"DSi_Password\": \"${{inputs. dsi_password }}\" }" > cypress.env.json
      working-directory: ./tests/Dfe.PlanTech.Web.E2ETests/

    - name: Build and test project
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./tests/Dfe.PlanTech.Web.E2ETests/
        browser: chrome
        config: baseUrl=${{ inputs.url }}

    - name: Store screenshots on test failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: ./tests/Dfe.PlanTech.Web.E2ETests/cypress/screenshots
        if-no-files-found: ignore

    - name: Store videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: ./tests/Dfe.PlanTech.Web.E2ETests/cypress/videos
        if-no-files-found: ignore