name: Azure IP Whitelist
description: Add or remove an IP Address to the Azure KV + SQL whitelist

inputs:
  ip_address:
    required: true
    type: string
  verb:
    required: true
    type: choice
    options:
      - "add"
      - "remove"
  az_resource_group:
    required: true
    type: string
  az_keyvault_name:
    required: true
    type: string
  az_ip_name:
    type: string
    default: "github_action"
  az_sql_database_server_name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Add to whitelist
      shell: bash
      run: echo "${{ inputs.az_sql_database_server_name}}" | base64