-- <summary>
-- Drop STS Users table.
-- </summary>
SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS STSUsers
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS STSTrackUsers
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS STSTrackAnsers
GO