name: Build DotNet App
description: Sets up .Net for specified version and builds application

inputs:
  dotnet_version:
    required: true
    type: string
  solution_filename:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Setup .NET Core SDK ${{ inputs.dotnet_version }}
      shell: bash
      run: echo "${{ inputs.solution_filename }}" | base64
