name: Back up database

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: 'Dev'
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to back up
        required: true
        type: choice
        options: ['Dev', 'Test', 'StagingUnprotected', 'ProductionUnprotected']
        default: 'Dev'

jobs:
  backup:
    environment: ${{ inputs.environment }}
    name: Back up database
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}

      - name: Install SqlPackage
        run: dotnet tool install --global Microsoft.SqlPackage

      - name: Get GitHub Runner IP
        id: whats-my-ip
        uses: ./.github/actions/whats-my-ip-address

      - name: Whitelist Runner for SQL Server
        uses: ./.github/actions/whitelisting-for-runner
        with:
          runner_ip: ${{ steps.whats-my-ip.outputs.ip }}
          az_aca_resource_group: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
          sql_server_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
          removeRules: 'false'

      - name: Export database
        run: |
          ACCESS_TOKEN="$(az account get-access-token \
            --resource https://database.windows.net/ \
            --query accessToken -o tsv)"

          sqlpackage /Action:Export \
            /SourceServerName:"tcp:${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}.database.windows.net,1433" \
            /SourceDatabaseName:"${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-sqldb" \
            /TargetFile:"db-$(date +%F).bacpac" \
            /AccessToken:"$ACCESS_TOKEN"

      - name: Save bacpac
        run: |
          az storage blob upload \
          --account-name plantechsqlbackups \
          --container-name sqlbackups \
          --name db-$(date +%F).bacpac \
          --file db-$(date +%F).bacpac \
          --auth-mode login

      - name: De-Whitelist Runner for SQL Server
        uses: ./.github/actions/whitelisting-for-runner
        with:
          runner-ip: ${{ steps.whats-my-ip.outputs.ip }}
          az-aca-resource-group: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
          sql-server-name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
          removeRules: 'true'
