name: Contentful Broken Link Checker

on:
  schedule:
    - cron: 0 1 * * 1-5
  workflow_dispatch:
    inputs:
      environment:
        description: Which Contentful environment to check for broken links
        required: true
        type: choice
        options: ['Dev', 'Tst', 'StagingUnprotected', 'ProductionUnprotected']
        default: 'StagingUnprotected'

jobs:
  check_broken_links:
    name: Contentful broken link checker
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'StagingUnprotected' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install export-processor deps
        working-directory: ./contentful/export-processor/
        run: npm ci

      - name: Install broken-link-checker dependencies
        working-directory: ./contentful/broken-link-checker/
        run: npm ci

      - name: Run get-links.js && checker.js
        working-directory: ./contentful/broken-link-checker/
        env:
          CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
          MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
          USE_PREVIEW: false
        run: npm run checker

      - name: Upload report files
        uses: actions/upload-artifact@v4
        with:
          name: report-files-${{ inputs.environment }}
          path: ./contentful/broken-link-checker/report/
          if-no-files-found: warn
