name: Copy of Production to Dev

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: choice
        options: ['Prod']
        default: 'Prod'
  push:
    branches: ['feature/322958/copy-prod-into-dev']
  
env:
  BACKUP_CONTAINER_NAME: sqlbackups
  SQL_BACKUP_FILE_NAME: ''
  SQL_BACKUP_FILE_NAME_SEARCH: ''
  SQL_TARGET_DATABASE: 's190p01-plantech-sqldb-old'
  USE_LATEST_IF_NOT_SPECIFIED: true

jobs:
  copydb:
    runs-on: ubuntu-latest
    environment: ${{  vars.AZ_TAG_ENVIRONMENT  }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Get GitHub Runner IP
        id: whats-my-ip
        uses: ./.github/actions/whats-my-ip-address

      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}

      - name: Prepare derived variables
        id: vars
        shell: bash
        run: | 
          set -euo pipefail
          IS_DR="${{ github.event_name == 'push' && true || inputs.is_dr }}"

          if [ "$IS_DR" = "true" ]; then
            DFE_PROJECT_NAME="pt-dr"
          else
            DFE_PROJECT_NAME="${{ secrets.DFE_PROJECT_NAME }}"
          fi

          RESOURCE_PREFIX_BACKUP="${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-backup" #notdf 
          RESOURCE_PREFIX_APP="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}" #could be df
          echo "RESOURCE_PREFIX_BACKUP=$RESOURCE_PREFIX_BACKUP" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_BACKUP_SHORT=${RESOURCE_PREFIX_BACKUP//-/}" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_APP_SHORT=${RESOURCE_PREFIX_APP//-/}" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_APP=$RESOURCE_PREFIX_APP" >> "$GITHUB_OUTPUT"

      - name: Restore DB from BACPAC
        uses: ./.github/actions/restore-db-from-bacpac
        with:
          resource_group_backup: ${{ steps.vars.outputs.RESOURCE_PREFIX_BACKUP }}
          resource_group_app: ${{ steps.vars.outputs.RESOURCE_PREFIX_APP }}
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          sql_server_name: ${{ steps.vars.outputs.RESOURCE_PREFIX_APP }}
          target_database: ${{ env.SQL_TARGET_DATABASE }} #Needs adding as a secret s190 ... -old (in Azure)
          storage_account: ${{ steps.vars.outputs.RESOURCE_PREFIX_BACKUP_SHORT }}
          container_name: ${{ env.BACKUP_CONTAINER_NAME }}
          bacpac_file: ${{ env.SQL_BACKUP_FILE_NAME }}
          bacpac_prefix: ${{ env.SQL_BACKUP_FILE_NAME_SEARCH }}
          use_latest_if_not_specified: ${{ env.USE_LATEST_IF_NOT_SPECIFIED }}