name: Copy of Production to Dev

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: choice
        options: ['Prod']
        default: 'Prod'
  push:
    branches: ['feature/322958/copy-prod-into-dev']
  
env:
  BACKUP_CONTAINER_NAME: sqlbackups
  SQL_BACKUP_FILE_NAME: ''
  SQL_BACKUP_FILE_NAME_SEARCH: ''
  SQL_TARGET_DATABASE: 's190d01-plantech-sqldb-prod-backup'
  USE_LATEST_IF_NOT_SPECIFIED: true

jobs:
  copydb:
    runs-on: ubuntu-latest
    environment: 'ProductionUnprotected'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Get GitHub Runner IP
        id: whats-my-ip
        uses: ./.github/actions/whats-my-ip-address

      - name: Prepare derived variables
        id: vars
        shell: bash
        run: | 
          set -euo pipefail

          RESOURCE_PREFIX_BACKUP="${{ vars.AZ_ENVIRONMENT_PROD }}${{ vars.DFE_PROJECT_NAME }}-backup"
          RESOURCE_PREFIX_DB="${{ vars.AZ_ENVIRONMENT_DEV }}${{ vars.DFE_PROJECT_NAME }}" 
          echo "RESOURCE_PREFIX_BACKUP=$RESOURCE_PREFIX_BACKUP" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_BACKUP_SHORT=${RESOURCE_PREFIX_BACKUP//-/}" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_DB_SHORT=${RESOURCE_PREFIX_DB//-/}" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_DB=$RESOURCE_PREFIX_DB" >> "$GITHUB_OUTPUT"

      - name: Restore DB from BACPAC
        uses: ./.github/actions/restore-db-from-bacpac
        with:
          backup_env: 'ProductionUnprotected'
          db_env: 'Dev'
          resource_group_backup: ${{ steps.vars.outputs.RESOURCE_PREFIX_BACKUP }}
          resource_group_db: ${{ steps.vars.outputs.RESOURCE_PREFIX_DB }}
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          sql_server_name: ${{ steps.vars.outputs.RESOURCE_PREFIX_DB }}
          target_database: ${{ env.SQL_TARGET_DATABASE }}
          storage_account: ${{ steps.vars.outputs.RESOURCE_PREFIX_BACKUP_SHORT }}
          container_name: ${{ env.BACKUP_CONTAINER_NAME }}
          bacpac_file: ${{ env.SQL_BACKUP_FILE_NAME }}
          bacpac_prefix: ${{ env.SQL_BACKUP_FILE_NAME_SEARCH }}
          use_latest_if_not_specified: ${{ env.USE_LATEST_IF_NOT_SPECIFIED }}
          delete_if_exists: true
          dev_client_id: ${{ secrets.DEV_CLIENT_ID }}
          dev_tenant_id: ${{ secrets.DEV_TENANT_ID }}
          dev_subscription_id: ${{ secrets.DEV_SUBSCRIPTION_ID }}
          prod_client_id: ${{ secrets.PROD_CLIENT_ID }}
          prod_tenant_id: ${{ secrets.PROD_TENANT_ID }}
          prod_subscription_id: ${{ secrets.PROD_SUBSCRIPTION_ID }}
