on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      artifact:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-deploy-${{ inputs.environment }}-azure-function
  cancel-in-progress: true

jobs:
  deploy-image:      
    runs-on: ubuntu-22.04
    name: Deploy .NET Azure Function App
    environment: ${{  inputs.environment }}
    env:
      AZURE_FUNCTIONAPP_NAME: "${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}contentfulfunction"
      AZURE_RESOURCEGROUP_NAME: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
      AZURE_STORAGEACCOUNT_NAME: "${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}funcstr"
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ./build

      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}
          az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}

      - name: Get workflow IP address
        id: whats-my-ip
        uses: ./.github/actions/whats-my-ip-address
        
      - name: Add Azure firewall rules
        shell: bash
        # The Azure Storage Account's name contains no hyphens, unlike almost all of our other resources
        # Therefore remove hyphens from the string before using it as the account name
        run: |
          az storage account network-rule add --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
                                              --account-name $(echo ${{ env.AZURE_STORAGEACCOUNT_NAME }} | sed -e "s/-//g") \
                                              --ip-address ${{ steps.whats-my-ip.outputs.ip }} &> /dev/null

      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./build
  
      - name: Remove Azure firewall rules
        shell: bash
        if: always()
        run: |
          az storage account network-rule remove --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
                                                 --account-name $(echo ${{ env.AZURE_STORAGEACCOUNT_NAME }} | sed -e "s/-//g") \
                                                 --ip-address ${{ steps.whats-my-ip.outputs.ip }} &> /dev/null
