name: Flush the Redis Cache

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to flush the redis cache on?
        required: true
        type: choice
        options: [ 'Dev', 'Tst', 'Staging', 'Production']
        default: 'Staging'

jobs:
  flush-redis-cache:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-22.04
    name: Flush Redis Cache on ${{ inputs.environment }}
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}

      - name: Flush Redis Cache
        uses: azure/CLI@v1
        id: azure
        with:
          azcliversion: 2.73.0
          inlineScript: |
            az redis flush --name ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }} --resource-group ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }} --yes
