name: Infrastructure - Backup Resources Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to run infrastructure deployment on:'
        required: true
        options: ['Dev', 'Tst', 'StagingUnprotected', 'ProductionUnprotected']
  push:
    branches:
      - disaster-recovery-e2e-terraform

env:
  BACKUP_CONTAINER_NAME_SQL: sqlbackups
  BACKUP_CONTAINER_NAME_TF: terraform
  BACKUP_CONTAINER_NAME_CONTENTFUL: contentful
  TF_WORKING_DIRECTORY: terraform/backups

jobs:
  set-vars:
    name: Prepare derived variables
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
    outputs:
      TF_RG: ${{ steps.set-vars.outputs.TF_RG }}
      TF_KV: ${{ steps.set-vars.outputs.TF_KV }}
      TF_SA: ${{ steps.set-vars.outputs.TF_SA }}
      B_RG: ${{ steps.set-vars.outputs.B_RG }}
      B_SA: ${{ steps.set-vars.outputs.B_SA }}

    steps:
      - name: Prepare derived variables
        id: set-vars
        shell: bash
        run: |
          TF_RG="${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-tf"
          TF_KV="${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-tf-kv"
          TF_SA_FULL="${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-tfstate"
          TF_SA="${TF_SA_FULL//-/}"
          B_RG="${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-backup"
          B_SA="${B_RG//-/}"

          echo "TF_RG=$TF_RG" >> "$GITHUB_OUTPUT"
          echo "TF_KV=$TF_KV" >> "$GITHUB_OUTPUT"
          echo "TF_SA=$TF_SA" >> "$GITHUB_OUTPUT"
          echo "B_RG=$B_RG" >> "$GITHUB_OUTPUT"
          echo "B_SA=$B_SA" >> "$GITHUB_OUTPUT"

  terraform:
    name: Terraform Apply
    needs: set-vars
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Terraform init
        id: init
        run: |
          echo "TF_RG='${{ needs.set-vars.outputs.TF_RG }}'"
          echo "TF_SA='${{ needs.set-vars.outputs.TF_SA }}'"
          terraform init \
            -backend-config="resource_group_name=${{ needs.set-vars.outputs.TF_RG }}" \
            -backend-config="storage_account_name=${{ needs.set-vars.outputs.TF_SA }}" \

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="backup_resource_group_name=${{ needs.set-vars.outputs.B_RG }}" \
            -var="backup_storage_account_name=${{ needs.set-vars.outputs.B_SA }}" \
            -var="backup_container_name_sql=${{ env.BACKUP_CONTAINER_NAME_SQL }}" \
            -var="backup_container_name_contentful=${{ env.BACKUP_CONTAINER_NAME_CONTENTFUL }}" \
            -var="backup_container_name_tf=${{ env.BACKUP_CONTAINER_NAME_TF }}"
