name: Infrastructure Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to run infrastructure deployment on:'
        required: true
        options: ['Dev', 'Tst', 'StagingUnprotected', 'ProductionUnprotected']
      is_dr:
        type: boolean
        default: false
        description: 'flag for using disaster recovery: adds -dr to all resource names'
      deploy-tf-backend:
        type: boolean
        default: false
        description: 'flag to deploy the tf backend resources in this workflow. Can also run "infrastructure-deploy-platform" first to do that separately instead'

env:
  IS_DR: ${{ github.event_name == 'workflow_dispatch' && inputs.is_dr || false }}
  ENVIRONMENT_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
  #containers in the backup storage acc (not created here; assumed to already exist)
  BACKUP_CONTAINER_NAME: sqlbackups
  #solution folders for terraform files
  TF_WORKING_DIRECTORY_APP: terraform/container-app
  TF_WORKING_DIRECTORY_DNS: terraform/dns-zone
  #sql restore optional vars
  SQL_BACKUP_FILE_NAME: '' #can specify specific file, but not necessary
  SQL_BACKUP_FILE_NAME_SEARCH: '' #can specify a file name search term, but not necessary
  USE_LATEST_IF_NOT_SPECIFIED: true

jobs:
  set-vars:
    name: Prepare derived variables
    environment:
      name: ${{ env.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    outputs:
      RESOURCE_PREFIX_BACKUP: ${{ steps.set-vars.outputs.RESOURCE_PREFIX_BACKUP }}
      RESOURCE_PREFIX_TF: ${{ steps.set-vars.outputs.RESOURCE_PREFIX_TF }}
      RESOURCE_PREFIX_APP: ${{ steps.set-vars.outputs.RESOURCE_PREFIX_APP }}
      RESOURCE_PREFIX_BACKUP_SHORT: ${{ steps.set-vars.outputs.RESOURCE_PREFIX_BACKUP_SHORT }}
      RESOURCE_PREFIX_TF_SHORT: ${{ steps.set-vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
      RESOURCE_PREFIX_APP_SHORT: ${{ steps.set-vars.outputs.RESOURCE_PREFIX_APP_SHORT }}
      
    steps:
      - name: Prepare derived variables
        id: set-vars
        shell: bash
        run: |
          #'plantech' plus 'dr' makes some other resource names too long particularly the sql security SA so shorten to 'pt'
          DFE_PROJECT_NAME = "${{ env.IS_DR == 'true' && format('{0}-dr', 'pt') || secrets.DFE_PROJECT_NAME }}"
          RESOURCE_PREFIX_BACKUP = "${secrets.AZ_ENVIRONMENT}${DFE_PROJECT_NAME}-backup"
          RESOURCE_PREFIX_TF = "${secrets.AZ_ENVIRONMENT}${DFE_PROJECT_NAME}-tf"
          RESOURCE_PREFIX_APP = "${secrets.AZ_ENVIRONMENT}${DFE_PROJECT_NAME}"

          RESOURCE_PREFIX_BACKUP = "${{ env.IS_DR == 'true' && format('{0}-dr', RESOURCE_PREFIX_BACKUP) || $RESOURCE_PREFIX_BACKUP }}"
          RESOURCE_PREFIX_TF = "${{ env.IS_DR == 'true' && format('{0}-dr', RESOURCE_PREFIX_TF) || $RESOURCE_PREFIX_TF }}"
          RESOURCE_PREFIX_APP = "${{ env.IS_DR == 'true' && format('{0}-dr', RESOURCE_PREFIX_APP) || $RESOURCE_PREFIX_APP }}"
          #shared module makes its own prefix from env and project so don't combine here
          PROJECT_PREFIX_APP = "${{ env.IS_DR == 'true' && format('{0}-dr', DFE_PROJECT_NAME) || DFE_PROJECT_NAME }}"

          RESOURCE_PREFIX_BACKUP_SHORT = "${RESOURCE_PREFIX_BACKUP//-/}"
          RESOURCE_PREFIX_TF_SHORT = "${RESOURCE_PREFIX_TF//-/}"
          RESOURCE_PREFIX_APP_SHORT = "${RESOURCE_PREFIX_APP//-/}"

          echo "RESOURCE_PREFIX_BACKUP=$RESOURCE_PREFIX_BACKUP" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_TF=$RESOURCE_PREFIX_TF" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_APP=$RESOURCE_PREFIX_APP" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_BACKUP_SHORT=$RESOURCE_PREFIX_BACKUP_SHORT" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_TF_SHORT=$RESOURCE_PREFIX_TF_SHORT" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_APP_SHORT=$RESOURCE_PREFIX_APP_SHORT" >> "$GITHUB_OUTPUT"


  deploy-tf-resources:
    name: Prepare derived variables
    needs: set-vars
    if: github.event.inputs.deploy-tf-backend == 'true'
    environment:
      name: ${{ env.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Deploy TF Resources
        uses: ./.github/actions/deploy-tf-resources
        with:
          environment: ${{ env.ENVIRONMENT_NAME }}
          az_location: ${{ vars.AZ_LOCATION }}
          tf_backend_resource_group: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF }}
          tf_container_name: ${{ env.TF_BACKEND_CONTAINER_NAME }} 
          tf_storage_acc_name: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          tf_keyvault_name: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          az_object_id: ${{ secrets.AZ_OBJECT_ID }}

 #here you need to check your tfvars in the terraform keyvault reflect what you want.
 #bare in mind that environment and project will be overridden by the code if present, and that image_tag is optional
  deploy-app:
    name: Prepare derived variables
    needs: [set-vars,deploy-tf-resources]
    environment:
      name: ${{ env.ENVIRONMENT_NAME }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.TF_WORKING_DIRECTORY_APP}}
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Whitelist Runner for TF keyvault
        uses: ./.github/actions/whitelisting-kv
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF }}
          keyvault-name: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          verb: 'add'

      - name: Whitelist Runner for TF storage
        uses: ./.github/actions/whitelisting-storage
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF }}
          account-name: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          verb: 'add'

      - name: Whitelist Runner for backup storage
        uses: ./.github/actions/whitelisting-storage
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_BACKUP }}
          account-name: ${{ needs.set-vars.outputs.RESOURCE_PREFIX_BACKUP_SHORT }}
          verb: 'add'

      - name: Get secret and clean tfvars file (PowerShell)
        shell: pwsh
        run: |
          ./scripts-workflow/get-and-normalise-tfvars.ps1 `
            -SecretName "${{ secrets.TF_SECRET_NAME }}" `
            -KeyVaultName "${{ needs.set-vars.outputs.RESOURCE_PREFIX_TF_SHORT }}" #fix

      - name: Terraform init
        id: init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ needs.setup.outputs.RESOURCE_PREFIX_TF }}"  \
            -backend-config="storage_account_name=${{ needs.setup.outputs.tf_backend_storage_account_name }}"  \
            -backend-config="container_name=${{ env.TF_BACKEND_CONTAINER_NAME }}"

      - name: Apply Terraform changes - container registry only
        id: apply-acr
        run: terraform apply -target=azurerm_resource_group.app_rg -target=azurerm_container_registry.acr_notshared -var-file="normalisedTerraformVars.tfvars" -auto-approve     
        #use tfvars or specify names? might need have to be tfvars unless moved into own folder

      - name: Promote Image
        id: promote_image
        uses: ./.github/actions/promote-image
        with:
          image_branch: ${{ env.ENVIRONMENT_NAME == 'ProductionUnprotected' && 'main' || 'development' }}
          acr_name: ${{ needs.setup.outputs.RESOURCE_PREFIX_APP_SHORT }}
          acr_login_server: ${{ needs.setup.outputs.RESOURCE_PREFIX_APP_SHORT }}.azurecr.io
          package_name: ${{ env.PACKAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Terraform changes
        id: apply
        run: terraform apply
              -var-file="normalisedTerraformVars.tfvars"
              -var="project_name=${{needs.setup.outputs.PROJECT_PREFIX_APP}}"
              -var="image_tag=${{steps.promote_image.outputs.image_tag}}"
              -var="workflow_runner_ip=${{ env.TF_VAR_github_ip }}" -auto-approve

      - name: Restore DB from BACPAC
        uses: ./.github/actions/restore-db-from-bacpac
        with:
          resource_group: ${{ needs.setup.outputs.RESOURCE_PREFIX_BACKUP }}
          sql_server_name: ${{ needs.setup.outputs.RESOURCE_PREFIX_APP_SHORT }}
          target_database: ${{ needs.setup.outputs.RESOURCE_PREFIX_APP_SHORT }}-sqldb
          storage_account: ${{ needs.setup.outputs.RESOURCE_PREFIX_BACKUP_SHORT }}
          container_name: ${{ env.BACKUP_CONTAINER_NAME }}
          bacpac_file: ${{ env.SQL_BACKUP_FILE_NAME }}
          bacpac_prefix: ${{ env.SQL_BACKUP_FILE_NAME_SEARCH }}
          use_latest_if_not_specified: ${{ env.USE_LATEST_IF_NOT_SPECIFIED }}

          #dns?
