name: Infrastructure Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to run infrastructure deployment on:'
        required: true
        options: ['Dev', 'Tst', 'StagingUnprotected', 'ProductionUnprotected']
      is_dr:
        type: boolean
        default: false
      deploy-image:
        type: boolean
        default: true
      apply-terraform:
        type: boolean
        default: true
      restore-db:
        type: boolean
        default: false
  push:
    branches:
      - disaster-recovery-e2e-terraform

env:
  ARM_USE_OIDC: true
  TF_BACKEND_CONTAINER_NAME: tfstate
  TF_BACKEND_KEY: terraform.tfstate
  BACKUP_CONTAINER_NAME: sqlbackups
  TF_WORKING_DIRECTORY_ACR: terraform/acr
  TF_WORKING_DIRECTORY_APP: terraform/container-app
  PACKAGE_NAME: plan-technology-for-your-school
  SQL_BACKUP_FILE_NAME: ''
  SQL_BACKUP_FILE_NAME_SEARCH: ''
  USE_LATEST_IF_NOT_SPECIFIED: true

jobs:
  image-and-acr:
    name: Apply ACR and promote image
    if: ${{ always() && !failure() && !cancelled() && (github.event_name == 'push' || inputs.deploy-image) }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
    permissions:
      id-token: write
      contents: read
    outputs:
      image_tag: ${{ steps.promote_image.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Prepare derived variables
        id: vars
        shell: bash
        run: |
          set -euo pipefail

          ENVIRONMENT_NAME="${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}"
          IS_DR="${{ github.event_name == 'push' && true || inputs.is_dr }}"

          if [ "$IS_DR" = "true" ]; then
            DFE_PROJECT_NAME="pt-dr"
          else
            DFE_PROJECT_NAME="${{ secrets.DFE_PROJECT_NAME }}"
          fi

          RESOURCE_PREFIX_TF="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}-tf"
          TF_KEYVAULT_NAME="${RESOURCE_PREFIX_TF}-kv"
          RESOURCE_PREFIX_APP="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}"

          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_TF=$RESOURCE_PREFIX_TF" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_TF_SHORT=${RESOURCE_PREFIX_TF//-/}" >> "$GITHUB_OUTPUT"

          echo "RESOURCE_PREFIX_APP_SHORT=${RESOURCE_PREFIX_APP//-/}" >> "$GITHUB_OUTPUT"
          echo "PROJECT_PREFIX_APP=$DFE_PROJECT_NAME" >> "$GITHUB_OUTPUT"
          echo "TF_KEYVAULT_NAME=$TF_KEYVAULT_NAME" >> "$GITHUB_OUTPUT"
          echo "IS_DR=$IS_DR" >> "$GITHUB_OUTPUT"

      - name: Get runner public IP
        id: whats-my-ip
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "ip=$IP" >> "$GITHUB_OUTPUT"
          echo "TF_VAR_github_ip=$IP" >> "$GITHUB_ENV"

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Whitelist Runner for TF keyvault
        uses: ./.github/actions/whitelist-kv
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}
          keyvault-name: ${{ steps.vars.outputs.TF_KEYVAULT_NAME }}
          verb: add

      - name: Whitelist Runner for TF storage
        uses: ./.github/actions/whitelist-storage
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}
          account-name: ${{ steps.vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          verb: add

      - name: Get secret and clean tfvars file
        shell: pwsh
        run: |
          ./.github/scripts/get-and-normalise-tfvars.ps1 `
            -SecretName "${{ secrets.TF_SECRET_NAME }}" `
            -KeyVaultName "${{ steps.vars.outputs.TF_KEYVAULT_NAME }}"

      - name: Test Vars
        shell: bash
        run: |
          echo "Using tfprefix"=${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}
          echo "Using tf storage"=${{ steps.vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          echo "Using project_name=${{ steps.vars.outputs.PROJECT_PREFIX_APP }}"
          echo "Using is_dr=${{ steps.vars.outputs.IS_DR }}"

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIRECTORY_APP }}
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}" \
            -backend-config="storage_account_name=${{ steps.vars.outputs.RESOURCE_PREFIX_TF_SHORT }}" \
            -backend-config="container_name=${{ env.TF_BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.TF_BACKEND_KEY }}"

      - name: Apply Terraform changes - RG & container registry only
        working-directory: ${{ env.TF_WORKING_DIRECTORY_APP }}
        run: |
          terraform plan -input=false \
            -target=azurerm_resource_group.app_rg \
            -target=azurerm_container_registry.acr_notshared \
            -var="is_dr=${{ steps.vars.outputs.IS_DR }}" \
            -var="project_name=${{ steps.vars.outputs.PROJECT_PREFIX_APP }}" \
            -var="azure_location=northeurope" \
            -var-file="../../normalisedTerraformVars.tfvars" \
            -out=tfplan

          terraform show -no-color tfplan | grep -A20 "azurerm_resource_group.app_rg" || true

          terraform apply -auto-approve -input=false tfplan

      - name: Promote Image
        id: promote_image
        uses: ./.github/actions/promote-image
        with:
          image_branch: ${{ steps.vars.outputs.ENVIRONMENT_NAME == 'ProductionUnprotected' && 'main' || 'development' }}
          acr_name: ${{ steps.vars.outputs.RESOURCE_PREFIX_APP_SHORT }}
          acr_login_server: ${{ steps.vars.outputs.RESOURCE_PREFIX_APP_SHORT }}.azurecr.io
          package_name: ${{ env.PACKAGE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  apply-terraform:
    name: Apply Terraform changes
    needs: [image-and-acr]
    if: ${{ always() && !failure() && !cancelled() && (github.event_name == 'push' || inputs.apply-terraform) }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Prepare derived variables
        id: vars
        shell: bash
        run: |
          set -euo pipefail

          IS_DR="${{ github.event_name == 'push' && true || inputs.is_dr }}"

          if [ "$IS_DR" = "true" ]; then
            DFE_PROJECT_NAME="pt-dr"
          else
            DFE_PROJECT_NAME="${{ secrets.DFE_PROJECT_NAME }}"
          fi

          RESOURCE_PREFIX_TF="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}-tf"
          RESOURCE_PREFIX_APP="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}"
          TF_KEYVAULT_NAME="${RESOURCE_PREFIX_TF}-kv"

          echo "PROJECT_PREFIX_APP=$DFE_PROJECT_NAME" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_TF=$RESOURCE_PREFIX_TF" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_TF_SHORT=${RESOURCE_PREFIX_TF//-/}" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_APP_SHORT=${RESOURCE_PREFIX_APP//-/}" >> "$GITHUB_OUTPUT"
          echo "TF_KEYVAULT_NAME=$TF_KEYVAULT_NAME" >> "$GITHUB_OUTPUT"
          echo "IS_DR=$IS_DR" >> "$GITHUB_OUTPUT"

      - name: Get runner public IP
        id: whats-my-ip
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "ip=$IP" >> "$GITHUB_OUTPUT"
          echo "TF_VAR_github_ip=$IP" >> "$GITHUB_ENV"

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Whitelist Runner for TF keyvault
        uses: ./.github/actions/whitelist-kv
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}
          keyvault-name: ${{ steps.vars.outputs.TF_KEYVAULT_NAME }}
          verb: add

      - name: Whitelist Runner for TF storage
        uses: ./.github/actions/whitelist-storage
        with:
          ip-address: ${{ steps.whats-my-ip.outputs.ip }}
          resource-group: ${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}
          account-name: ${{ steps.vars.outputs.RESOURCE_PREFIX_TF_SHORT }}
          verb: add

      - name: Get secret and clean tfvars file
        shell: pwsh
        run: |
          ./.github/scripts/get-and-normalise-tfvars.ps1 `
            -SecretName "${{ secrets.TF_SECRET_NAME }}" `
            -KeyVaultName "${{ steps.vars.outputs.TF_KEYVAULT_NAME }}"

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIRECTORY_APP }}
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ steps.vars.outputs.RESOURCE_PREFIX_TF }}" \
            -backend-config="storage_account_name=${{ steps.vars.outputs.RESOURCE_PREFIX_TF_SHORT }}" \
            -backend-config="container_name=${{ env.TF_BACKEND_CONTAINER_NAME }}" \
            -backend-config="key=${{ env.TF_BACKEND_KEY }}"


            #because the shared module for container app does not output the container env, and the azure front door private link in the shared waf module needs it
            #we must make it first so we can reference with a data block.
      - name: Apply Terraform changes - main hosting only
        working-directory: ${{ env.TF_WORKING_DIRECTORY_APP }}
        run: |
          terraform plan -auto-approve -input=false \
            -target=module.main_hosting \
            -var="is_dr=${{ steps.vars.outputs.IS_DR }}" \
            -var="project_name=${{ steps.vars.outputs.PROJECT_PREFIX_APP }}" \
            -var="image_tag=${{ needs.image-and-acr.outputs.image_tag }}" \
            -var="workflow_runner_ip=${{ env.TF_VAR_github_ip }}"
            -var="azure_location=northeurope" \
            -var-file="../../normalisedTerraformVars.tfvars" \
            -out=tfplanmh

            terraform show -no-color tfplanmh || true

            terraform apply -auto-approve -input=false tfplanmh

      - name: Apply Terraform changes - rest of app
        working-directory: ${{ env.TF_WORKING_DIRECTORY_APP }}
        run: |
          terraform plan -auto-approve -input=false \
            -var="is_dr=${{ steps.vars.outputs.IS_DR }}" \
            -var="project_name=${{ steps.vars.outputs.PROJECT_PREFIX_APP }}" \
            -var="image_tag=${{ needs.image-and-acr.outputs.image_tag }}" \
            -var="workflow_runner_ip=${{ env.TF_VAR_github_ip }}" \
            -var="azure_location=northeurope" \
            -var-file="../../normalisedTerraformVars.tfvars" \
            -out=tfplanapp

            terraform show -no-color tfplanapp || true

            terraform apply -auto-approve -input=false tfplanapp

  restore-db:
    name: Restore DB from BACPAC
    needs: [apply-terraform]
    if: ${{ always() && !failure() && !cancelled() && (github.event_name == 'push' || inputs.restore-db) }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Prepare derived variables
        id: vars
        shell: bash
        run: |
          set -euo pipefail

          IS_DR="${{ github.event_name == 'push' && true || inputs.is_dr }}"

          if [ "$IS_DR" = "true" ]; then
            DFE_PROJECT_NAME="pt-dr"
          else
            DFE_PROJECT_NAME="${{ secrets.DFE_PROJECT_NAME }}"
          fi

          RESOURCE_PREFIX_BACKUP="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}-backup"
          RESOURCE_PREFIX_APP="${{ secrets.AZ_ENVIRONMENT }}${DFE_PROJECT_NAME}"

          echo "RESOURCE_PREFIX_BACKUP=$RESOURCE_PREFIX_BACKUP" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_BACKUP_SHORT=${RESOURCE_PREFIX_BACKUP//-/}" >> "$GITHUB_OUTPUT"
          echo "RESOURCE_PREFIX_APP_SHORT=${RESOURCE_PREFIX_APP//-/}" >> "$GITHUB_OUTPUT"

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Restore DB from BACPAC
        uses: ./.github/actions/restore-db-from-bacpac
        with:
          resource_group: ${{ steps.vars.outputs.RESOURCE_PREFIX_BACKUP }}
          sql_server_name: ${{ steps.vars.outputs.RESOURCE_PREFIX_APP_SHORT }}
          target_database: ${{ steps.vars.outputs.RESOURCE_PREFIX_APP_SHORT }}-sqldb
          storage_account: ${{ steps.vars.outputs.RESOURCE_PREFIX_BACKUP_SHORT }}
          container_name: ${{ env.BACKUP_CONTAINER_NAME }}
          bacpac_file: ${{ env.SQL_BACKUP_FILE_NAME }}
          bacpac_prefix: ${{ env.SQL_BACKUP_FILE_NAME_SEARCH }}
          use_latest_if_not_specified: ${{ env.USE_LATEST_IF_NOT_SPECIFIED }}
