name: Infrastructure Deploy - Full

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options: ['Dev', 'Tst', 'Staging', 'Production']
      is_dr:
        type: boolean
        default: true

env:
  ARM_USE_OIDC: true
  AZ_ACA_RESOURCE_GROUP: ${{ inputs.is_dr && format('{0}-dr', secrets.AZ_ACA_RESOURCE_GROUP) || secrets.AZ_ACA_RESOURCE_GROUP }}
  AZ_KEYVAULT_NAME: ${{ secrets.AZ_ACA_RESOURCE_GROUP }}-kv
  TF_BACKEND_RESOURCE_GROUP: ${{ inputs.is_dr && format('{0}-dr', secrets.TF_BACKEND_RESOURCE_GROUP) || secrets.TF_BACKEND_RESOURCE_GROUP }}
  TF_BACKEND_CONTAINER_NAME: tfstate
  TF_BACKEND_KEY: terraform.tfstate
  TF_SECRETS_KEYVAULT_NAME: ${{secrets.TF_BACKEND_RESOURCE_GROUP}}-kv

jobs:
  setup:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    name: Pipeline Setup
    runs-on: ubuntu-22.04
    outputs:
      az_sa_costing_name: ${{ steps.set-vars.outputs.az_sa_costing_name }}
      tf_backend_storage_account_name: ${{ steps.set-vars.outputs.tf_backend_storage_account_name }}
      acr_name: ${{ steps.set-vars.outputs.acr_name }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.7

    - name: Login with AZ
      uses: ./actions/azure-login
      with:
        az_tenant_id: ${{ secrets.az_tenant_id }}
        az_subscription_id: ${{ secrets.az_subscription_id }}
        az_client_id: ${{ secrets.az_client_id }}

    - name: Get GitHub Runner IP
      id: whats-my-ip
      uses: ./.github/actions/whats-my-ip-address

    - name: Set GitHub Runner IP to TF Var
      shell: bash
      run: |
        echo "TF_VAR_github_ip=${{ steps.whats-my-ip.outputs.ip}}" >> $GITHUB_ENV

    - name: Prepare env vars using removed hyphen
      shell: bash
      run: |
          # Remove hyphens from base resource group
          CLEAN_VAR=${AZ_ACA_RESOURCE_GROUP//-/}

          # Compute derived variables
          AZ_SA_COSTING_NAME="${CLEAN_VAR}costing"
          TF_BACKEND_STORAGE_ACCOUNT_NAME="${CLEAN_VAR}tfstate"
          ACR_NAME="${CLEAN_VAR}"
          COSTING_STORAGE_ACCOUNT_NAME="${CLEAN_VAR}costing"

          # Export as step outputs for downstream jobs
          echo "az_sa_costing_name=$AZ_SA_COSTING_NAME" >> $GITHUB_OUTPUT
          echo "tf_backend_storage_account_name=$TF_BACKEND_STORAGE_ACCOUNT_NAME" >> $GITHUB_OUTPUT
          echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT
          echo "costings_name=COSTING_STORAGE_ACCOUNT_NAME" >> $GITHUB_OUTPUT
  
  bootstrap:
    needs: setup
    uses: ./.github/jobs/bootstrap.yml
    with:
      environment: ${{ inputs.environment }}
      az_location: ${{ vars.AZ_LOCATION }}
      tf_backend_resource_group: ${{ needs.setup.outputs.tf_backend_storage_account_name }}
      tf_container_name: ${{ env.TF_BACKEND_CONTAINER_NAME }}
      tf_storage_acc_name: ${{ needs.setup.outputs.tf_backend_storage_account_name }}
      tf_keyvault_name: ${{ env.TF_SECRETS_KEYVAULT_NAME }}

  terraform-platform:
    needs: bootstrap
    uses: ./.github/jobs/tf-platform.yml
    with:
      environment: ${{ inputs.environment }}
      az_location: ${{ vars.AZ_LOCATION }}
      workflow_runner_ip: ${{ env.TF_VAR_github_ip }}
      az_resource_group: ${{ env.AZ_ACA_RESOURCE_GROUP }}
      tf_backend_resource_group: ${{ needs.setup.outputs.tf_backend_storage_account_name }}
      tf_container_name: ${{ env.TF_BACKEND_CONTAINER_NAME }}
      tf_storage_acc_name: ${{ needs.setup.outputs.tf_backend_storage_account_name  }}
      tf_keyfile_name: ${{ env.TF_BACKEND_KEY }}
      az_acr_name: ${{ needs.setup.outputs.acr_name }}
      costings_name: ${{ needs.setup.outputs.costings_name }}

  promote-image:
    needs: [setup, terraform-platform]
    uses: ./.github/jobs/promote-image.yml
    with:
      image_branch: ${{ inputs.environment == 'Production' && 'main' || 'development' }}
      acr_name: ${{ needs.setup.outputs.acr_name }}
    secrets: inherit


  terraform-plan:
    needs: [bootstrap, terraform-platform, promote-image]
    uses: ./.github/jobs/tf-app-plan.yml
    with:
      environment: ${{ inputs.environment }}
      image_tag: ${{ needs.promote-image.outputs.image_tag }}
      workflow_runner_ip: ${{ TF_VAR_github_ip }}
    secrets: inherit

  deploy-terraform:
    needs: terraform-plan
    uses: ./.github/jobs/tf-app-apply.yml
    with:
      environment: ${{ inputs.environment }}
      image_tag: ${{ needs.promote-image.outputs.image_tag }}
      workflow_runner_ip: ${{ TF_VAR_github_ip }}
