name: Infrastructure Deploy - load backup image/db only

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'The environment to run infrastructure deployment on:'
        required: true
        options: ['Dev', 'Tst', 'StagingUnprotected', 'ProductionUnprotected']
      is_dr:
        type: boolean
        default: false
        description: 'flag for using disaster recovery: adds -dr to all resource names'
  push:
     branches:
       - disaster-recovery-e2e-terraform

env:
  IS_DR: ${{ github.event_name == 'workflow_dispatch' && inputs.is_dr || true }}
  ENVIRONMENT_NAME: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
  ARM_USE_OIDC: true
  TF_BACKEND_CONTAINER_NAME: tfstate
  TF_BACKEND_KEY: terraform.tfstate
  
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

  ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
  GHR: plan-technology-for-your-school

jobs:
  image:
    name: Promote image from GHR to ACR based on branch name
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'Dev' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.az_tenant_id }}
          az_subscription_id: ${{ secrets.az_subscription_id }}
          az_client_id: ${{ secrets.az_client_id }}

      - name: Prepare derived variables
        id: set-vars
        shell: bash
        run: |
          BASE_PREFIX="${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}"

          if [ "${{ env.IS_DR }}" = "true" ]; then
            BASE_PREFIX_FULL="${BASE_PREFIX}-dr"
          else
            BASE_PREFIX_FULL="$BASE_PREFIX"
          fi

          echo "resource-prefix=$BASE_PREFIX_FULL" >> "$GITHUB_OUTPUT"

      - name: Promote Image
        id: promote_image
        uses: ./.github/actions/promote-image
        with:
          image_branch: ${{ inputs.environment == 'ProductionUnprotected' && 'main' || 'development' }}
          acr_name: ${{ steps.set-vars.outputs.resource-prefix }}
          image_name: ${{ env.GHR }}
          ghcr_token: ${{ secrets.GHCR_READ_TOKEN }}
#output ${{ steps.promote_image.outputs.image_tag }}
