name: QA Visualiser Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "development" ]
    paths:
      - "qa-visualiser/**"
      - ".github/workflows/qa-viz-tests.yml"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        working-directory: ./qa-visualiser
        run: uv python install

      - name: Install requirements
        working-directory: ./qa-visualiser
        run: uv sync

      - name: Run tests
        working-directory: ./qa-visualiser
        run: uv run pytest
